spring:
  profiles:
    active: local
server:
  port: 8010
---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: library-events-listener-group
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: nonprod
  kafka:
    template:
      default-topic: library-events
    consumer:
      bootstrap-servers: localhost:9095,localhost:9096,localhost:9097
      key-serializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
      ssl:
        trust-store-location: file:/System/Volumes/Data/Dilip/udemy/kafka-for-developers-using-spring-boot/ssl/client.truststore.jks
        trust-store-password: password
        key-store-location: file:/System/Volumes/Data/Dilip/udemy/kafka-for-developers-using-spring-boot/ssl/client.keystore.jks
        key-store-password: password
      properties:
        acks: all
        retries: 10
        retry.backoff.ms: 1000
        security:
          protocol: SSL
        ssl.endpoint.identification.algorithm:

---
spring:
  config:
    activate:
      on-profile: prod
  kafka:
    consumer:
      bootstrap-servers: prod:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer

